#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          openarena
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for OpenArena server
# Description:       Startup script for OpenArena server
### END INIT INFO

# Installation:
# Move this file to /etc/init.d/openarena
# Make it executable: sudo chmod +x /etc/init.d/openarena
# Start at boot: sudo update-rc.d openarena defaults
# Manual start: sudo /etc/init.d/openarena start

# Change the next 4 lines to suit where you installed OpenArena, and which user is running the OpenArena server
DAEMON=/opt/openarena/oa_ded.i386
OPTIONS="+set fs_game baseoa +set dedicated 1 +set fs_homepath /home/q3user/openarena +set net_port 27960 +set com_hunkmegs 128 +exec server.cfg +map aggressor"
USER=q3user
GROUP=q3user

NAME=openarena

set -e

# Get LSB functions
. /lib/lsb/init-functions

# Check that the package is still installed
test -x $DAEMON || exit 0

case "$1" in
    start)
        log_begin_msg "Starting service $NAME..."
        umask 002
        if start-stop-daemon --start --quiet --background --chuid $USER:$GROUP --exec $DAEMON -- $OPTIONS; then
            log_end_msg 0
        else
            log_end_msg $?
        fi
        ;;

    stop)
        log_begin_msg "Stopping service $NAME..."
        if start-stop-daemon --stop --quiet --oknodo --exec $DAEMON; then
                log_end_msg 0
        else
                log_end_msg $?
        fi
        ;;

    restart)
        log_begin_msg "Restarting service $NAME..."
        start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
        sleep 3
        start-stop-daemon --start --quiet --background --chuid $USER:$GROUP --exec $DAEMON -- $OPTIONS
        log_end_msg $? 
        ;;

    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
        exit 1
        ;;
esac
exit 0